[Distribution]
Distribution=arch
Architecture=x86-64

[Output]
CompressOutput=zstd
SplitArtifacts=
OutputDirectory=mkosi.output

[Content]
UnifiedKernelImages=unsigned
Locale=en_US.UTF-8
LocaleMessages=en_US.UTF-8
Keymap=us
Timezone=UTC
RootPassword=root
RootShell=/usr/bin/fish

[Build]
ToolsTree=yes
ToolsTreeProfiles=misc,runtime
Environment="SYSTEMD_REPART_MKFS_OPTIONS_BTRFS=-n 32k -O squota"
WorkspaceDirectory=/tmp/archosi/mkosi.workspace
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.pkgcache
BuildDirectory=mkosi.builddir
WithNetwork=yes

[Validation]
Verity=no
SignExpectedPcr=no

[Runtime]
Firmware=uefi
RAM=4G
