[Content]
Packages=
        7zip
        amd-ucode
        arch-install-scripts
        base
        base-devel
        bash-completion
        bat
        bind
        btop
        btrfs-progs
        bubblewrap
        buildah
        bun
        caddy
        capnproto
        curl
        dog
        dosfstools
        duf
        dust
        efibootmgr
        fd
        fish
        fzf
        git
        go
        gptfdisk
        hck
        hexyl
        hyperfine
        intel-ucode
        iperf3
        iproute2
        ipython
        jaq
        just
        kubectl
        less
        linux
        linux-firmware
        lua
        man-db
        mdbook
        mtr
        neovim
        nftables
        nmap
        onefetch
        openai-codex
        openssh
        pacman-contrib
        parallel
        pnpm
        podman
        podman-compose
        postgresql
        python
        rathole
        rclone
        reflector
        ripgrep
        rsync
        rust
        sd
        shfmt
        sqlite
        stress-ng
        sudo
        systemd
        systemd-ukify
        tokei
        translate-shell
        transmission-cli
        uv
        valkey
        xfsprogs
        yazi
        zellij
        zoxide
        zstd
