[Unit]
ConditionPathExists=/etc/kernel/secure-boot.key
ConditionPathExists=/etc/kernel/secure-boot.crt

[Service]
ExecStartPre=/usr/lib/systemd/systemd-sbsign sign --private-key=/etc/kernel/secure-boot.key --certificate=/etc/kernel/secure-boot.crt --output=/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /usr/lib/systemd/boot/efi/systemd-bootx64.efi
