[Partition]
Type=esp
Label=ESP
Format=vfat
CopyFiles=/boot:/
CopyFiles=/efi:/
SizeMinBytes=1G
SizeMaxBytes=1G
MountPoint=/efi:noauto,x-systemd.automount,x-systemd.idle-timeout=60s,umask=0077,noexec,nodev,nosuid,nosymfollow,errors=remount-ro
