[Output]
RepartDirectories=
RepartDirectories=mkosi.repart
RepartDirectories=../../mkosi.repart

[Validation]
SecureBoot=yes
SecureBootKey=mkosi.extra/etc/kernel/secure-boot.key
SecureBootCertificate=mkosi.extra/etc/kernel/secure-boot.crt
